const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
let drivers = [];
let statusFilter = "pending";
let selectedDriverId = null;
let toastTimer;

const statusLabels = { pending: "Pendiente", active: "Activo", cancelled: "Cancelado" };
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[character]));
const initials = (driver) => `${driver.firstName?.[0] || ""}${driver.lastName?.[0] || ""}`.toUpperCase();
const dateLabel = (value) => value ? new Date(value).toLocaleString("es-DO", { dateStyle:"medium", timeStyle:"short" }) : "—";

function toast(message) { const element=$("#admin-toast"); element.textContent=message; element.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>element.classList.remove("show"),3200); }
async function fetchJson(url, options={}) { let response; try { response=await fetch(url,{method:options.method||"GET",headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{})},body:options.body?JSON.stringify(options.body):undefined}); } catch { throw new Error("No se pudo conectar con TAXOTE."); } const body=await response.json().catch(()=>({})); if(!response.ok) throw new Error(body.error||"No se pudo procesar la solicitud."); return body; }

function openMenu(){ $("#side-menu").classList.add("open"); $("#drawer-overlay").hidden=false; $("#menu-button").setAttribute("aria-expanded","true"); }
function closeMenu(){ $("#side-menu").classList.remove("open"); $("#drawer-overlay").hidden=true; $("#menu-button").setAttribute("aria-expanded","false"); }
$("#menu-button").addEventListener("click",()=>$("#side-menu").classList.contains("open")?closeMenu():openMenu());
$("#close-menu").addEventListener("click",closeMenu); $("#drawer-overlay").addEventListener("click",closeMenu);

function updateCounts(){ $("#pending-count").textContent=drivers.filter(d=>d.status==="pending").length; $("#active-count").textContent=drivers.filter(d=>d.status==="active").length; $("#cancelled-count").textContent=drivers.filter(d=>d.status==="cancelled").length; $("#total-count").textContent=drivers.length; }
function filteredDrivers(){ const query=$("#driver-search").value.trim().toLocaleLowerCase("es"); return drivers.filter(driver=>(statusFilter==="all"||driver.status===statusFilter)&&(!query||[driver.name,driver.phone,driver.email,driver.vehicleType,driver.vehicleBrand,driver.vehicleModel,driver.vehicleColor,driver.vehiclePlate].join(" ").toLocaleLowerCase("es").includes(query))); }
function renderDrivers(){ updateCounts(); const visible=filteredDrivers(); $("#result-count").textContent=`${visible.length} ${visible.length===1?"resultado":"resultados"}`; $("#drivers-empty").hidden=visible.length!==0; $("#drivers-body").innerHTML=visible.map(driver=>`<tr data-driver-id="${escapeHtml(driver.id)}"><td><div class="driver-cell"><span class="table-avatar">${escapeHtml(initials(driver))}</span><div><b>${escapeHtml(driver.name)}</b><small>${escapeHtml(driver.id)}</small></div></div></td><td>${escapeHtml(driver.phone)}<br><small>${escapeHtml(driver.email)}</small></td><td><span class="vehicle-cell"><b>${escapeHtml(driver.vehicleBrand)} ${escapeHtml(driver.vehicleModel)}</b><small>${escapeHtml(driver.vehicleType)} · ${escapeHtml(driver.vehicleColor)}</small></span></td><td><span class="plate-chip">${escapeHtml(driver.vehiclePlate)}</span></td><td><span class="status-badge status-${driver.status}">${statusLabels[driver.status]}</span></td><td>${escapeHtml(dateLabel(driver.createdAt))}</td><td><button class="view-driver" type="button">Ver expediente</button></td></tr>`).join(""); $$("#drivers-body tr").forEach(row=>row.addEventListener("click",()=>openDriver(row.dataset.driverId))); }

async function loadDrivers(announce=false){ const button=$("#refresh-drivers"); button.disabled=true; try { drivers=await fetchJson("/api/admin/drivers"); renderDrivers(); const requestedDriver=new URLSearchParams(location.search).get("driver"); if(requestedDriver&&drivers.some(driver=>driver.id===requestedDriver)&&selectedDriverId!==requestedDriver)openDriver(requestedDriver); if(announce) toast("Lista de conductores actualizada."); } catch(error){ toast(error.message); } finally { button.disabled=false; } }
function setImage(linkSelector,imageSelector,url){ const link=$(linkSelector); if(!url){link.hidden=true;return;} link.hidden=false; link.href=url; $(imageSelector).src=`${url}?v=${Date.now()}`; }
async function openDriver(id){ selectedDriverId=id; try { const {driver}=await fetchJson(`/api/admin/drivers/${encodeURIComponent(id)}`); $("#detail-avatar").textContent=initials(driver); $("#detail-id").textContent=`EXPEDIENTE ${driver.id}`; $("#detail-name").textContent=driver.name; $("#detail-date").textContent=`Registrado ${dateLabel(driver.createdAt)}`; const badge=$("#detail-status"); badge.textContent=statusLabels[driver.status]; badge.className=`status-badge status-${driver.status}`; $("#detail-email").textContent=driver.email; $("#detail-phone").textContent=driver.phone; $("#detail-cedula").textContent=driver.cedula; $("#detail-login").textContent=driver.lastLoginAt?dateLabel(driver.lastLoginAt):"Nunca"; $("#detail-vehicle-type").textContent=driver.vehicleType; $("#detail-vehicle-brand").textContent=driver.vehicleBrand; $("#detail-vehicle-model").textContent=driver.vehicleModel; $("#detail-color").textContent=driver.vehicleColor; $("#detail-plate").textContent=driver.vehiclePlate; $("#detail-points").textContent=driver.pointsBalance || 0; $("#edit-points-input").value=driver.pointsBalance || 0; setImage("#id-front-link","#detail-id-front",driver.documents.idFront); setImage("#id-back-link","#detail-id-back",driver.documents.idBack); setImage("#vehicle-link","#detail-vehicle-photo",driver.documents.vehicle); $("#activate-driver").hidden=driver.status==="active"; $("#cancel-driver").hidden=driver.status==="cancelled"; $("#driver-detail-modal").hidden=false; document.body.style.overflow="hidden"; } catch(error){ toast(error.message); } }

async function savePoints(){ if(!selectedDriverId)return; const points=Number($("#edit-points-input").value); try { await fetchJson(`/api/admin/drivers/points`,{method:"POST",body:{driverId:selectedDriverId,points}}); toast("Puntos actualizados correctamente."); await openDriver(selectedDriverId); await loadDrivers(); } catch(error){ toast(error.message); } }
$("#save-points").addEventListener("click",savePoints);
function closeDetail(){ $("#driver-detail-modal").hidden=true; document.body.style.overflow=""; selectedDriverId=null; }
async function setDriverStatus(status){ if(!selectedDriverId)return; const button=status==="active"?$("#activate-driver"):$("#cancel-driver"); button.disabled=true; try { await fetchJson(`/api/admin/drivers/${encodeURIComponent(selectedDriverId)}/status`,{method:"POST",body:{status}}); toast(status==="active"?"Conductor activado.":"Cuenta del conductor cancelada."); await loadDrivers(); await openDriver(selectedDriverId); } catch(error){ toast(error.message); } finally { button.disabled=false; } }

$$('[data-status-filter]').forEach(button=>button.addEventListener("click",()=>{statusFilter=button.dataset.statusFilter; $$('[data-status-filter]').forEach(item=>item.classList.toggle("selected",item===button)); renderDrivers();}));
$("#driver-search").addEventListener("input",renderDrivers); $("#refresh-drivers").addEventListener("click",()=>loadDrivers(true));
$("#close-driver-detail").addEventListener("click",closeDetail); $("#driver-detail-modal").addEventListener("pointerdown",event=>{if(event.target===$("#driver-detail-modal"))closeDetail();});
$("#activate-driver").addEventListener("click",()=>setDriverStatus("active")); $("#cancel-driver").addEventListener("click",()=>setDriverStatus("cancelled"));
$("#delete-driver").addEventListener("click",async()=>{if(!selectedDriverId||!confirm("¿Eliminar permanentemente este registro y sus fotografías?"))return; try { await fetchJson(`/api/admin/drivers/${encodeURIComponent(selectedDriverId)}`,{method:"DELETE"}); closeDetail(); await loadDrivers(); toast("Registro del conductor eliminado."); } catch(error){toast(error.message);} });
document.addEventListener("keydown",event=>{if(event.key==="Escape"){if(!$("#driver-detail-modal").hidden)closeDetail();else closeMenu();}});
loadDrivers();
