
const $=s=>document.querySelector(s);
let lastAlertId=0,alertTimer;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const dt=v=>v?new Date(v).toLocaleString("es-DO",{dateStyle:"medium",timeStyle:"short"}):"—";
async function api(url,opt={}){const r=await fetch(url,{method:opt.method||"GET",credentials:"include",headers:{Accept:"application/json"}});const b=await r.json().catch(()=>({}));if(r.status===401){location.replace("/admin-login");throw new Error("Sesión expirada");}if(!r.ok)throw new Error(b.error||"Error");return b;}
function showAlert(a){const box=$("#wallet-alert");box.innerHTML=`${esc(a.title)}<small>${esc(a.body)}</small>`;box.hidden=false;clearTimeout(alertTimer);alertTimer=setTimeout(()=>box.hidden=true,5000);}
async function loadWallet(){try{const data=await api("/api/admin/wallet"),drivers=data.drivers||[],audits=data.audits||[],alerts=data.alerts||[];$("#wallet-driver-count").textContent=drivers.length;$("#wallet-total-points").textContent=drivers.reduce((n,d)=>n+Number(d.points||0),0);$("#wallet-alert-count").textContent=alerts.length;$("#wallet-body").innerHTML=drivers.length?drivers.map(d=>`<tr><td><b>${esc(d.name)}</b></td><td>${esc(d.id)}</td><td>${d.lastRechargePoints?`${d.lastRechargePoints} puntos`:"—"}</td><td>${dt(d.lastRechargeAt)}</td><td><span class="points-pill">${d.points}</span></td></tr>`).join(""):'<tr><td colspan="5">No hay conductores.</td></tr>';$("#wallet-audit").innerHTML=audits.length?audits.map(a=>`<div class="audit-row"><b>${esc(a.driverName)}</b><span>${a.oldPoints} → ${a.newPoints}</span><span class="delta ${a.delta<0?"negative":"positive"}">${a.delta>0?"+":""}${a.delta}</span><span>${esc(a.reason)}</span><span>${dt(a.createdAt)}</span></div>`).join(""):"<p style='padding:18px'>Sin cambios registrados.</p>";if(alerts[0]&&alerts[0].id>lastAlertId){if(lastAlertId)showAlert(alerts[0]);lastAlertId=alerts[0].id;}}catch(e){console.error(e);}}
$("#refresh-wallet")?.addEventListener("click",loadWallet);$("#menu-toggle")?.addEventListener("click",()=>{$("#side-menu").classList.add("open");$("#drawer-overlay").hidden=false;});$("#close-menu")?.addEventListener("click",()=>{$("#side-menu").classList.remove("open");$("#drawer-overlay").hidden=true;});$("#drawer-overlay")?.addEventListener("click",()=>$("#close-menu").click());$("#wallet-logout")?.addEventListener("click",async e=>{e.preventDefault();try{await fetch("/api/admin/logout",{method:"POST",credentials:"include"});}catch{}location.replace("/admin-login");});
loadWallet();setInterval(loadWallet,4000);
