plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.taxote.driver'
    compileSdk 35

    signingConfigs {
        taxoteDriver {
            storeFile rootProject.file('../.android-user/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId 'com.taxote.driver'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '1.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.taxoteDriver
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.1.2')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
